export const votingFactoryAbi = [
  "function owner() view returns (address)",
  "function treasury() view returns (address)",
  "function eventCreationFeeWei() view returns (uint256)",
  "function setTreasury(address newTreasury)",
  "function setEventCreationFee(uint256 newFeeWei)",
  "function createEvent((string title,string description,string[] options)[] proposals,string title,string description,uint8 mode,uint256 startTime,uint256 endTime,bool isPublic,address[] allowedVoters) payable returns (uint256)",
  "function deleteEvent(uint256 eventId)",
  "function authorizeVoter(uint256 eventId, address voter)",
  "function castVote(uint256 eventId, uint256 proposalId, uint8 optionIndex)",
  "function getEvents() view returns ((uint256 id,string title,string description,uint8 mode,address creator,uint256 startTime,uint256 endTime,bool isActive,bool isPublic,uint256 proposalCount,uint256 allowedVoterCount)[])",
  "function getEvent(uint256 eventId) view returns ((uint256 id,string title,string description,uint8 mode,address creator,uint256 startTime,uint256 endTime,bool isActive,bool isPublic,uint256 proposalCount,uint256 allowedVoterCount))",
  "function getEventProposals(uint256 eventId) view returns ((uint256 id,uint256 eventId,string title,string description,string[] options,uint256[] voteCounts)[])",
  "function getVoteRecord(uint256 eventId, uint256 proposalId, address voter) view returns (bool hasVoted, uint8 optionIndex)",
  "function canVoteInEvent(uint256 eventId, address voter) view returns (bool)",
  "function getAllowedVoters(uint256 eventId) view returns (address[])",
  "event EventCreated(uint256 indexed eventId, address indexed creator, uint8 mode)",
  "event EventDeleted(uint256 indexed eventId, address indexed actor)",
  "event VoterAuthorized(uint256 indexed eventId, address indexed voter, address indexed actor)",
  "event VoteCast(uint256 indexed eventId, uint256 indexed proposalId, address indexed voter, uint8 optionIndex)",
] as const;
